name: Deploy KHQR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build & Push Image
    outputs:
      git_sha: ${{ steps.set-sha.outputs.git_sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set Git SHA
        id: set-sha
        run: |
          GIT_SHA=$(git rev-parse --short=7 HEAD)
          echo "git_sha=$GIT_SHA" >> $GITHUB_OUTPUT
          echo "GIT_SHA=$GIT_SHA" >> $GITHUB_ENV

      - name: Debug Git SHA
        run: echo "Git SHA is ${{ env.GIT_SHA }}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            sivejin/khqr-service:sha-${{ env.GIT_SHA }}
          dockerfile: Dockerfile

  notify-telegram:
    runs-on: ubuntu-latest
    needs: build-and-push
    name: 📢 Notify Telegram
    steps:
      - name: Send Telegram Message (Build Success)
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 Build Successful!
            Service: KHQR
            Commit SHA: ${{ needs.build-and-push.outputs.git_sha }}
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Workflow: ${{ github.workflow }}